.clang-tidy
.github/workflows/ADev.yml
CMakeLists.txt
build.sh
projects/ABuild/File.cpp
projects/ABuild/include/ABuild/File.hpp
projects/ABuild/main.cpp
projects/Catch2/include/Catch2/catch.hpp

Run clang tidy during build

---

.github/workflows/ADev.yml
build.sh

Remove conditions for running formatting and analysis checks

---

.github/workflows/ADev.yml
build.sh

Add stress testing

---

CMakeLists.txt

Resolve overriding /W3 to /W4 warning with MSVC

---

CMakeLists.txt

Set minimum CMake version to 3.15

---

projects/ABuild/File.cpp
projects/ABuild/include/ABuild/File.hpp
projects/ABuild/test/FileTest.cpp

Add file build type detection

---

CMakeLists.txt
projects/ABuild/File.cpp
projects/ABuild/Source.cpp
projects/ABuild/include/ABuild.hpp
projects/ABuild/include/ABuild/File.hpp
projects/ABuild/include/ABuild/Source.hpp
projects/ABuild/test/FileTest.cpp
projects/ABuild/test/SourceTest.cpp
projects/ABuild/test/TestFile.cpp
projects/ABuild/test/TestFile.hpp

File record metadata to detect file change

---

build.sh
projects/ABuild/test/SourceTest.cpp

Intentionally broken build

---

.github/workflows/ADev.yml
build.sh

Move installation to build.sh

---

CMakeLists.txt
projects/ACore/Numeric.cpp
projects/ACore/include/ACore.hpp
projects/ACore/include/ACore/Numeric.hpp
projects/ACore/test/NumericTest.cpp
projects/ACore/test/pch.hpp

A core add project #58

---

CMakeLists.txt
projects/ACore/Numeric.cpp
projects/ACore/include/ACore.hpp
projects/ACore/include/ACore/ACoreModule.hpp
projects/ACore/include/ACore/ForwardIterator.hpp
projects/ACore/include/ACore/Numeric.hpp
projects/ACore/test/ForwardIteratorTest.cpp
projects/ACore/test/NumericTest.cpp
projects/Catch2/include/Catch2/catch.hpp

Add ForwardIterator

---

build.sh

Fix result detection in documentation check

---

CMakeLists.txt
projects/ACore/include/ACore.hpp
projects/ACore/include/ACore/BitMask.hpp
projects/ACore/include/ACore/ForwardIterator.hpp
projects/ACore/test/BitMaskTest.cpp

Add BitMask

---

.github/workflows/ADev.yml
CMakeLists.txt
build.sh
projects/ABenchmarks/BitMaskBenchmark.cpp
projects/ABenchmarks/pch.hpp
projects/ACore/include/ACore/BitMask.hpp
projects/ACore/test/BitMaskTest.cpp
projects/Catch2/Catch2.cpp

Add benchmarks #45

---

CMakeLists.txt
projects/ACore/include/ACore.hpp
projects/ACore/include/ACore/Reference.hpp
projects/ACore/test/ReferenceTest.cpp

Add Reference

---

CMakeLists.txt
projects/ACore/include/ACore.hpp
projects/ACore/include/ACore/RandomAccessIterator.hpp
projects/ACore/test/RandomAccessIteratorTest.cpp

Add RandomAccessIterator

---

CMakeLists.txt
build.sh

Add precompiled headers

---

CMakeLists.txt
projects/ACore/include/ACore.hpp
projects/ACore/include/ACore/UndoStack.hpp
projects/ACore/test/UndoStackTest.cpp

Add UndoStack

---

CMakeLists.txt
build.sh
projects/ABenchmarks/VariantBenchmark.cpp
projects/ACore/Process.cpp
projects/ACore/include/ACore.hpp
projects/ACore/include/ACore/Process.hpp
projects/ACore/test/ProcessTest.cpp
projects/tiny-process-library/.clang-format
projects/tiny-process-library/.gitignore
projects/tiny-process-library/.gitlab-ci.yml
projects/tiny-process-library/CMakeLists.txt
projects/tiny-process-library/LICENSE
projects/tiny-process-library/README.md
projects/tiny-process-library/examples.cpp
projects/tiny-process-library/process.cpp
projects/tiny-process-library/process.hpp
projects/tiny-process-library/process_unix.cpp
projects/tiny-process-library/process_win.cpp
projects/tiny-process-library/tests/CMakeLists.txt
projects/tiny-process-library/tests/io_test.cpp
projects/tiny-process-library/tests/multithread_test.cpp
projects/tiny-process-library/tests/open_close_test.cpp

Add process #84

---

CMakeLists.txt
build.sh

Disable precompiled headers in coverage build

---

.gitignore
CMakeLists.txt
build.sh

Add memory sanitizer

---

CMakeLists.txt
build.sh

Add address sanitizer #93

---

build.sh

Simplify MSVC detection

---

.github/workflows/ADev.yml

Add sanitizers to ADev.yaml

---

projects/ACore/test/ExceptionTest.cpp

Exclude assertion in ExceptionTest from Debug

---

build.sh

Always print benchmark log

---

projects/ABenchmarks/DataIndexMapBenchmark.cpp

Disable check against hash buckets version of DataIndexMap

---

build.sh

Run analysis in parallel

---

.github/workflows/ADev.yml
build.sh

Add separate build steps

---

CMakeLists.txt
projects/ACore/include/ACore/DictionaryBase.hpp
projects/ACore/test/DictionaryTest.cpp
projects/AFile/PersistentDictionary.cpp
projects/AFile/PersistentDictionaryData.cpp
projects/AFile/include/AFile.hpp
projects/AFile/include/AFile/PersistentDictionary.hpp
projects/AFile/include/AFile/PersistentDictionaryData.hpp
projects/AFile/test/PersistentDictionaryTest.cpp

Adds persistent (afile::File based) implementation of acore::Dictionary class to AFile module.
Resolves #137

Add persistent dictionary #137

---

projects/AFile/PersistentDictionaryData.cpp
projects/AFile/include/AFile.hpp
projects/AFile/include/AFile/File.hpp
projects/AFile/include/AFile/PersistentVector.hpp
projects/AFile/test/FileTest.cpp
projects/AFile/test/PersistentVectorTest.cpp

Removes File::loadValue and allows File::value to throw.
Resolves #143

Remove load value from file #143

---

CMakeLists.txt
projects/ACore/include/ACore/ACoreModule.hpp
projects/AFile/include/AFile/AFileModule.hpp
projects/AFile/pch.hpp
projects/AGraph/Graph.cpp
projects/AGraph/README.md
projects/AGraph/include/AGraph.hpp
projects/AGraph/include/AGraph/AGraphModule.hpp
projects/AGraph/include/AGraph/Common.hpp
projects/AGraph/include/AGraph/Edge.hpp
projects/AGraph/include/AGraph/Element.hpp
projects/AGraph/include/AGraph/Graph.hpp
projects/AGraph/include/AGraph/GraphBase.hpp
projects/AGraph/include/AGraph/GraphData.hpp
projects/AGraph/include/AGraph/Node.hpp
projects/AGraph/pch.hpp
projects/AGraph/test/CommonTest.cpp
projects/AGraph/test/EdgeTest.cpp
projects/AGraph/test/ElementTest.cpp
projects/AGraph/test/GraphTest.cpp
projects/AGraph/test/NodeTest.cpp
projects/AGraph/test/pch.hpp

Adds graph implementation to AGraph and related classes.
Resolves #148 
Resolves #149 
Resolves #150

Add node #148

---

CMakeLists.txt
projects/AFile/test/FileTest.cpp
projects/AFile/test/PersistentDataIndexMapTest.cpp
projects/AFile/test/PersistentVectorTest.cpp
projects/AGraph/PersistentGraph.cpp
projects/AGraph/PersistentGraphData.cpp
projects/AGraph/include/AGraph.hpp
projects/AGraph/include/AGraph/PersistentGraph.hpp
projects/AGraph/include/AGraph/PersistentGraphData.hpp
projects/AGraph/test/PersistentGraphTest.cpp

Add PersistentGraph class to AGraph.
Resolves #156

Add PersistentGraph

---

.github/workflows/ADev.yml
README.md
build.sh
projects/ADbStudio/.gitignore
projects/ADbStudio/jest.config.js
projects/ADbStudio/package-lock.json
projects/ADbStudio/package.json
projects/ADbStudio/tests/unit/main.spec.js

Add tests to ADbStudio and add builds, tests and packaging to ADev workflow.
Resolves #160

Add a db studio to build #160

---

CMakeLists.txt
build.sh
projects/ACore/include/ACore/Variant.hpp
projects/ADb/Value.cpp
projects/ADb/include/ADb.hpp
projects/ADb/include/ADb/ADbModule.hpp
projects/ADb/include/ADb/Value.hpp
projects/ADb/pch.hpp
projects/ADb/test/ValueTest.cpp
projects/ADb/test/pch.hpp

Adds database Value class.
Resolves #169

Add database value #169

---

projects/ACore/include/ACore/Variant.hpp

Adds missing [[nodiscard]] to functions in acore::Variant.
Resolves #173

Add missing nodiscard

---

CMakeLists.txt
README.md
projects/ADb/README.md
projects/ADb/include/ADb.hpp
projects/ADb/include/ADb/KeyValue.hpp
projects/ADb/test/KeyValueTest.cpp

Add helper struct adb::KeyValue.
Resolves #175

Add adb::KeyValue

---

CMakeLists.txt
projects/ACore/test/DataIndexMapTest.cpp
projects/ACore/test/ExceptionTest.cpp
projects/ADb/Element.cpp
projects/ADb/KeyValue.cpp
projects/ADb/include/ADb/Element.hpp
projects/ADb/include/ADb/KeyValue.hpp
projects/ADb/test/ElementTest.cpp
projects/ADb/test/KeyValueTest.cpp
projects/AGraph/test/GraphTest.cpp

Adds the database Element.
Resolves #177

Add database element #177

---

CMakeLists.txt
projects/ACore/include/ACore/DataStream.hpp
projects/ACore/include/ACore/DataStreamBuffer.hpp
projects/ADb/Result.cpp
projects/ADb/include/ADb/Element.hpp
projects/ADb/include/ADb/Result.hpp
projects/ADb/test/ElementTest.cpp
projects/ADb/test/ResultTest.cpp
projects/ADb/test/ValueTest.cpp

Add Database Result
Resolves #184

Add Database Result

---

projects/ADbStudio/src/views/Scene.vue

Command textarea will be resized only in vertical direction.
Resolves #183

Fixed resizing

---

projects/ADbStudio/src/App.vue
projects/ADbStudio/src/components/base/BaseButton.vue
projects/ADbStudio/src/main.js
projects/ADbStudio/src/views/Scene.vue
projects/ADbStudio/tests/unit/TestUtils.js
projects/ADbStudio/tests/unit/base/BaseButton.spec.js

Added BaseButton and used it in main scene.
Resolves #186

Create and use base button #186

---

CMakeLists.txt
projects/ADb/Condition.cpp
projects/ADb/include/ADb/Condition.hpp
projects/ADb/include/ADb/Result.hpp
projects/ADb/test/ConditionTest.cpp

Add database query condition.
Resolves #188

Add Condition

---

CMakeLists.txt
projects/ADb/Query.cpp
projects/ADb/include/ADb/Query.hpp
projects/ADb/test/QueryTest.cpp

Adds insert node to Query class.
Resolves #192

Add insert node query

---

projects/ADb/Query.cpp
projects/ADb/include/ADb/Query.hpp
projects/ADb/test/QueryTest.cpp

Adds overloads to query that accepts another query.
Resolves #196

Add subquery

---

projects/ADbStudio/src/components/base/BaseButton.vue
projects/ADbStudio/src/components/base/BaseIcon.vue
projects/ADbStudio/src/components/base/BaseMessage.vue
projects/ADbStudio/src/components/scene/ADbView.vue
projects/ADbStudio/src/components/scene/Edge.vue
projects/ADbStudio/src/components/scene/Node.vue
projects/ADbStudio/src/components/scene/SearchField.vue
projects/ADbStudio/src/components/transitions/FadeTransition.vue
projects/ADbStudio/src/locales/cz.json
projects/ADbStudio/src/locales/en.json
projects/ADbStudio/src/store/modules/scene.js
projects/ADbStudio/src/views/Scene.vue
projects/ADbStudio/tests/unit/TestUtils.js
projects/ADbStudio/tests/unit/base/BaseMessage.spec.js
projects/ADbStudio/tests/unit/scene/SearchField.spec.js
projects/ADbStudio/tests/unit/transitions/FadeTransition.spec.js
projects/ADbStudio/tests/unit/views/scene.spec.js

Added display of search results in ADbView, added search messages in the main scene.
Resolves #198

Search elements in ADbView

---

.github/workflows/ADev.yml
CMakeLists.txt
projects/ADb/InsertEdgeFromQuery.cpp
projects/ADb/InsertEdgeQuery.cpp
projects/ADb/InsertQuery.cpp
projects/ADb/Placeholders.cpp
projects/ADb/QueryData.cpp
projects/ADb/SelectQuery.cpp
projects/ADb/SubQuery.cpp
projects/ADb/include/ADb.hpp
projects/ADb/include/ADb/InsertEdgeFromQuery.hpp
projects/ADb/include/ADb/InsertEdgeQuery.hpp
projects/ADb/include/ADb/InsertQuery.hpp
projects/ADb/include/ADb/Placeholders.hpp
projects/ADb/include/ADb/Queries.hpp
projects/ADb/include/ADb/Query.hpp
projects/ADb/include/ADb/QueryData.hpp
projects/ADb/include/ADb/SelectQuery.hpp
projects/ADb/include/ADb/SubQuery.hpp
projects/ADb/test/InsertQueryTest.cpp
projects/ADb/test/QueryDataTest.cpp
projects/ADb/test/QueryTest.cpp

Add query placeholders and refactor queries into multiple classes.
Resolves #200

Add query placeholders #200

---

.github/workflows/ADev.yml

Disable sanitize memory check due to random failures.
Resolves #

Disable-sanitize-memory-check-#206

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md
.github/workflows/ADev.yml
CMakeLists.txt
build.sh

Experimental fix to random failure of sanitize memory build
Resolves #206

Fix-Sanitize-memory-sometimes-fail-#206

---

projects/ADbStudio/src/components/base/BaseBox.vue
projects/ADbStudio/src/components/base/BaseIcon.vue
projects/ADbStudio/src/components/scene/ADbView.vue
projects/ADbStudio/src/components/scene/DataWrapper.vue
projects/ADbStudio/src/components/scene/Edge.vue
projects/ADbStudio/src/components/scene/Element.vue
projects/ADbStudio/src/components/scene/ElementData.vue
projects/ADbStudio/src/components/scene/Elements.vue
projects/ADbStudio/src/components/scene/Node.vue
projects/ADbStudio/src/components/transitions/SlideYTransition.vue
projects/ADbStudio/src/locales/cz.json
projects/ADbStudio/src/locales/en.json
projects/ADbStudio/src/store/modules/scene.js
projects/ADbStudio/src/views/Scene.vue
projects/ADbStudio/tests/unit/TestUtils.js
projects/ADbStudio/tests/unit/base/BaseBox.spec.js
projects/ADbStudio/tests/unit/scene/AdbView.spec.js
projects/ADbStudio/tests/unit/scene/DataWrapper.spec.js
projects/ADbStudio/tests/unit/scene/Edge.spec.js
projects/ADbStudio/tests/unit/scene/Elements.spec.js
projects/ADbStudio/tests/unit/transitions/SlideYTransition.spec.js
projects/ADbStudio/tests/unit/views/scene.spec.js

Added posibility of having multiple edges in one place. Improved edge style. Improved elements data style.
Resolves #204 
Resolves #210

Multiple edges in one place + edge style

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md

Removed placeholders and left blank space.
Resolves #214

Fix templates placeholders #214

---

projects/ADbStudio/tests/unit/layout/MainFooter.spec.js
projects/ADbStudio/tests/unit/layout/MainHeader.spec.js
projects/ADbStudio/tests/unit/layout/__snapshots__/MainFooter.spec.js.snap
projects/ADbStudio/tests/unit/layout/__snapshots__/MainHeader.spec.js.snap
projects/ADbStudio/tests/unit/scene/AdbView.spec.js
projects/ADbStudio/tests/unit/scene/DataWrapper.spec.js
projects/ADbStudio/tests/unit/scene/Edge.spec.js
projects/ADbStudio/tests/unit/scene/EdgeListData.spec.js
projects/ADbStudio/tests/unit/scene/LeftPanel.spec.js
projects/ADbStudio/tests/unit/scene/Node.spec.js
projects/ADbStudio/tests/unit/scene/NodeListData.spec.js
projects/ADbStudio/tests/unit/scene/RightPanel.spec.js
projects/ADbStudio/tests/unit/scene/__snapshots__/AdbView.spec.js.snap
projects/ADbStudio/tests/unit/scene/__snapshots__/DataWrapper.spec.js.snap
projects/ADbStudio/tests/unit/scene/__snapshots__/Edge.spec.js.snap
projects/ADbStudio/tests/unit/scene/__snapshots__/EdgeListData.spec.js.snap
projects/ADbStudio/tests/unit/scene/__snapshots__/LeftPanel.spec.js.snap
projects/ADbStudio/tests/unit/scene/__snapshots__/Node.spec.js.snap
projects/ADbStudio/tests/unit/scene/__snapshots__/NodeListData.spec.js.snap
projects/ADbStudio/tests/unit/scene/__snapshots__/RightPanel.spec.js.snap
projects/ADbStudio/tests/unit/views/__snapshots__/scene.spec.js.snap
projects/ADbStudio/tests/unit/views/scene.spec.js

Added snapshot testing.
Resolves #233

Added snapshot testing

---

.github/workflows/ADev.yml
build.sh

Fixes the clang 10 installation failure on GitHub's Ubuntu image.
Resolves #242

Fix clang 10 installation failure on Ubuntu #242

---

README.md
projects/ADbQuery/ADb.json
projects/ADbQuery/README.md
projects/ADbStudio/README.md

Adds the ADb.json schema and the readme describing it.
Resolves #238

Add ADbQuery schema #238

---

.gitignore
CMakeLists.txt
README.md
projects/ADbQuery/common.js
projects/ADbQuery/index.js
projects/ADbQuery/package-lock.json
projects/ADbQuery/package.json

Add node.js ADbQuery project and custom CMake build command as prerequisite of of ADb project.
Resolves #241

Add ADbQuery build #241

---

projects/ADbStudio/package-lock.json
projects/ADbStudio/package.json

Updated packages to resolve security vulnerability alert.
Resolves #246

Update ADbStudio packages #246

---

projects/ADbQuery/Parser.js
projects/ADbQuery/babel.config.cjs
projects/ADbQuery/index.js
projects/ADbQuery/package-lock.json
projects/ADbQuery/package.json
projects/ADbQuery/test/Parser.test.js

Adds parser producing AST (abstract syntax tree) of ADb.json
Resolves #248

Add ADbQuery parser #248

---

projects/ADbQuery/README.md
projects/ADbQuery/src/analyze_expression.js
projects/ADbQuery/src/analyzer_common.js
projects/ADbQuery/test/analyze_expression.test.js

Add serialization ast #260

---

.github/pull_request_template.md

[devops] Add PR template #269

---

LICENSE

[devops] Change license to Apache 2.0 #267

---

projects/abuild/high_level_design.md

[abuild] Add high level design #273

---

projects/abuild/high_level_design.md

[abuild] Add component design to HLD #275

---

projects/abuild/high_level_design.md
projects/atest/high_level_design.md

[atest] Add high level design #283

---

projects/atest/README.md
projects/atest/atest.ixx
projects/atest/test/atest_test.cpp

[atest] Add test() #298

---

projects/atest/README.md
projects/atest/atest.ixx
projects/atest/test/atest_suite_test.cpp
projects/atest/test/atest_test.cpp

[atest] Add suite() #300

---

projects/atest/README.md
projects/atest/atest.ixx
projects/atest/test/atest_test.cpp

[atest] Add test runner #303

---

projects/atest/atest.ixx
projects/atest/test/atest_test.cpp

[atest] Add expect()

---

projects/astl/high_level_design.md

[astl] Add high level design #313

---

.gitignore
README.md
build.bat
build.sh

[devops] Add build script #281

---

projects/atest/atest.ixx

[atest] Fix tests in other files are not registered #319

---

build.bat
build.sh
projects/atest/atest.ixx
projects/atest/test/atest_nomain_test.cpp
projects/atest/test/atest_test.cpp
projects/atest/test/expect_tobe.cpp
projects/atest/test/expect_tothrow.cpp

[atest] Add Expect::toThrow() #312

---

projects/atest/atest.ixx
projects/atest/test/expect_tothrow.cpp

[atest] Fix Expect::toThrow() undefined reference to type_info (MSVC) #324

---

projects/atest/README.md

[atest] Fix link to ASTL in README #327

---

projects/atest/atest.ixx
projects/atest/test/expect_tobe.cpp
projects/atest/test/expect_tothrow.cpp

[atest] Add toFail() expectation #329

---

projects/atest/README.md
projects/atest/atest.ixx
projects/atest/test/expect_tothrow.cpp

[atest] Add printer #306

---

projects/atest/atest.ixx

[atest] Add source location #308

---

projects/atest/README.md
projects/atest/atest.ixx

[atest] Add time measurement #309

---

projects/atest/atest.ixx

[atest] Add reporter #334

---

projects/atest/README.md
projects/atest/atest.ixx

[atest] Add documentation #339

---

projects/atest/README.md
projects/atest/atest.ixx
projects/atest/test/atest_test.cpp

[atest] Run in main #346

---

projects/atest/README.md
projects/atest/atest.ixx
projects/atest/test/expect_tothrow_test.cpp

[atest] Add toThrow(value) #347

---

projects/atest/README.md
projects/atest/atest.ixx
projects/atest/test/expect_tobe_test.cpp

[atest] Remove toFail() value overload #348

---

clang-tidy.sh
compile_flags.txt
projects/atest/atest.ixx
projects/atest/test/bad_test_suite.cpp

[devops] Fix clang-tidy __GLIBC_USE undefined #354

---

projects/atest/README.md
projects/atest/printer.cpp
projects/atest/test/atest_test.cpp
projects/atest/test/bad_test_suite.cpp
projects/atest/test/expect_tobe_test.cpp
projects/atest/test/expect_tomatch_test.cpp
projects/atest/test/expect_tothrow_test.cpp
projects/atest/test/printer_test.cpp
projects/atest/test_runner.cpp

[atest] Add color #352

---

clang-tidy.sh
compile_flags.txt
projects/atest/README.md
projects/atest/data.cpp
projects/atest/printer.cpp
projects/atest/test/atest_test.cpp
projects/atest/test_runner.cpp

[atest] Add sorting of test suites #358

---

projects/acore/high_level_design.md

[acore] Add CommandLine HLD #363

---

projects/atest/atest.cpp
projects/atest/data.cpp
projects/atest/expect.cpp
projects/atest/expect_base.cpp
projects/atest/expect_tomatch.cpp
projects/atest/expect_tothrow.cpp
projects/atest/matcher.cpp
projects/atest/printer.cpp
projects/atest/reporter.cpp
projects/atest/source_location.cpp
projects/atest/stringify.cpp
projects/atest/test_runner.cpp

[atest] Add in-code documentation #366

---

projects/atest/expect_tomatch.cpp
projects/atest/test/expect_tobe_test.cpp

[atest] Fix error c2090 function returns array #371

---

projects/atest/matcher.cpp

[atest] Fix expected and actual are reversed in toThrow() #373

---

build.bat
build.sh
projects/acore/README.md
projects/acore/acore.cpp
projects/acore/acore_common.cpp
projects/acore/commandline.cpp
projects/acore/commandline_option.cpp
projects/acore/test/commandline_option_test.cpp
projects/acore/test/commandline_test.cpp
projects/atest/README.md

[acore] Add command line #287

---

projects/atest/data.cpp
projects/atest/printer.cpp
projects/atest/reporter.cpp
projects/atest/test/main.cpp
projects/atest/test_runner.cpp

[atest] Print failures at the end again #375

---

.clang-format

[devops] Update clang-format to version 12 #384

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/main.cpp
projects/abuild/test/main.cpp
projects/acore/module.modulemap
projects/atest/test/main.cpp

[abuild] Add project files #286

---

projects/rapidjson/include/rapidjson/document.h

[devops] Fix RapidJSON does not compile in modules #397

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/environment_scanner.cpp
projects/abuild/test/environment_scanner_test.cpp
projects/rapidjson/include/rapidjson.hpp

[abuild] Add environment scanner #400

---

build.bat
build.sh
projects/acore/test/commandline_option_test.cpp
projects/acore/test/commandline_test.cpp
projects/acore/test/process_test.cpp
projects/atest/README.md
projects/atest/atest.cpp
projects/atest/data.cpp
projects/atest/expect.cpp
projects/atest/expect_base.cpp
projects/atest/expect_tomatch.cpp
projects/atest/expect_tothrow.cpp
projects/atest/test/assert_test.cpp
projects/atest/test/expect_tobe_test.cpp
projects/atest/test/expect_tomatch_test.cpp
projects/atest/test/expect_tothrow_test.cpp
projects/atest/test/main.cpp
projects/atest/test/printer_test.cpp
projects/atest/test_runner.cpp

[atest] Add assert #410

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/test/build_cache_test.cpp

[abuild] Add build cache #426

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/project.cpp
projects/abuild/test/project_test.cpp

[abuild] Add Project #428

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/settings.cpp
projects/abuild/test/settings_test.cpp

[abuild] Add Settings #431

---

build.bat
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/file.cpp
projects/abuild/test/file_test.cpp

[abuild] Add File #434

---

projects/atest/stringify.cpp
projects/atest/test/main.cpp
projects/atest/test/printer_test.cpp

[atest] Add stringifying for std::pair #437

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/module.cpp
projects/abuild/test/module_test.cpp

[abuild] Add module #441

---

projects/abuild/build_cache.cpp
projects/abuild/test/header_test.cpp
projects/abuild/test/source_test.cpp

[abuild] Add tests for Source and Header #443

---

projects/astl/generator/main.js
projects/astl/generator/package-lock.json
projects/astl/include/astl.hpp

[astl] Fix coroutines header name #445

---

projects/abuild/project_scanner.cpp

[abuild] Cannot use reverse iterator of std::vector #404

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/dependency.cpp
projects/abuild/test/dependency_test.cpp
projects/abuild/test/tokenizer_test.cpp
projects/abuild/token.cpp
projects/abuild/tokenizer.cpp

[abuild] Add Tokenizer #453

---

build.bat
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/error.cpp
projects/abuild/test/build_cache_test.cpp
projects/abuild/warning.cpp

[abuild] Add error reporting to BuildCache #456

---

projects/abuild/dependency.cpp
projects/abuild/test/dependency_test.cpp

[abuild] Add DependencyVisibility #458

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/code_scanner.cpp
projects/abuild/module.cpp
projects/abuild/test/abuild_test_utilities.cpp
projects/abuild/test/build_cache_test.cpp
projects/abuild/test/code_scanner_headers_test.cpp
projects/abuild/test/code_scanner_modules_test.cpp
projects/abuild/test/code_scanner_sources_test.cpp
projects/abuild/test/dependency_test.cpp
projects/abuild/test/file_test.cpp
projects/abuild/test/header_test.cpp
projects/abuild/test/main.cpp
projects/abuild/test/module_test.cpp
projects/abuild/test/project_scanner_headers_test.cpp
projects/abuild/test/project_scanner_projects_test.cpp
projects/abuild/test/project_scanner_sources_test.cpp
projects/abuild/test/project_test.cpp
projects/abuild/test/settings_test.cpp
projects/abuild/test/source_test.cpp
projects/abuild/test/tokenizer_test.cpp

[abuild] Add CodeScanner #455

---

projects/abuild/build_cache.cpp
projects/abuild/module.cpp
projects/abuild/test/code_scanner_modules_test.cpp
projects/abuild/test/module_test.cpp

[abuild] Dynamically allocate ModulePartition #460

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/dependency_scanner.cpp
projects/abuild/module.cpp
projects/abuild/test/dependency_scanner_test.cpp
projects/abuild/test/module_test.cpp

[abuild] Add DependencyScanner #463

---

build.bat
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/build_cache_index.cpp
projects/abuild/dependency_scanner.cpp
projects/abuild/module.cpp
projects/abuild/test/code_scanner_modules_test.cpp
projects/abuild/test/dependency_scanner_test.cpp
projects/abuild/test/module_test.cpp

[abuild] Add BuildCacheIndex #465

---

projects/abuild/build_cache.cpp
projects/abuild/project.cpp
projects/abuild/project_scanner.cpp
projects/abuild/settings.cpp
projects/abuild/test/abuild_test_utilities.cpp
projects/abuild/test/project_scanner_projects_test.cpp
projects/abuild/test/project_test.cpp
projects/abuild/test/settings_test.cpp

[abuild] Add Project type #467

---

projects/abuild/test/tokenizer_test.cpp
projects/abuild/tokenizer.cpp

[abuild] Fix Tokenizer reads modules from quoted strings #471

---

projects/abuild/test/tokenizer_test.cpp
projects/abuild/tokenizer.cpp

[abuild] Tokenizer throws an exception with comment at the end of file #475

---

projects/abuild/build_cache.cpp
projects/abuild/project.cpp
projects/abuild/test/project_scanner_projects_test.cpp

[abuild] Add sources and headers to Project #477

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/build_cache_index.cpp
projects/abuild/build_graph.cpp
projects/abuild/build_task.cpp
projects/abuild/file.cpp
projects/abuild/main.cpp
projects/abuild/test/build_graph_test.cpp
projects/abuild/test/build_task_test.cpp

[abuild] Add BuildGraph #416

---

projects/abuild/build_graph.cpp
projects/abuild/code_scanner.cpp
projects/abuild/dependency.cpp
projects/abuild/dependency_scanner.cpp
projects/abuild/test/build_graph_test.cpp
projects/abuild/test/code_scanner_headers_test.cpp
projects/abuild/test/code_scanner_sources_test.cpp
projects/abuild/test/dependency_scanner_test.cpp

[abuild] Support external source include #480

---

projects/abuild/build_cache.cpp
projects/abuild/build_cache_index.cpp
projects/abuild/build_graph.cpp
projects/abuild/build_task.cpp
projects/abuild/test/build_graph_test.cpp
projects/abuild/test/build_task_test.cpp

[abuild] Add import STL build task #488

---

projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/code_scanner.cpp
projects/abuild/project_scanner.cpp
projects/abuild/settings.cpp
projects/abuild/test/settings_test.cpp

[abuild] Make Settings non static #491

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/main.cpp
projects/abuild/override.cpp
projects/abuild/project_scanner.cpp
projects/abuild/settings.cpp
projects/abuild/test/build_cache_test.cpp
projects/abuild/test/build_graph_test.cpp
projects/abuild/test/code_scanner_headers_test.cpp
projects/abuild/test/code_scanner_modules_test.cpp
projects/abuild/test/code_scanner_sources_test.cpp
projects/abuild/test/dependency_scanner_test.cpp
projects/abuild/test/override_settings_test.cpp
projects/abuild/test/override_test.cpp
projects/abuild/test/project_scanner_headers_test.cpp
projects/abuild/test/project_scanner_projects_test.cpp
projects/abuild/test/project_scanner_sources_test.cpp
projects/abuild/test/project_test.cpp
projects/abuild/test/source_test.cpp
projects/abuild_old/abuild.cpp

[abuild] Add user override #415

---

build.bat
build.sh
projects/abuild/abuild.cpp
projects/abuild/build_cache.cpp
projects/abuild/sdk.cpp
projects/abuild/sdk_scanner.cpp
projects/abuild/test/build_cache_test.cpp
projects/abuild/test/sdk_scanner_test.cpp
projects/abuild/test/sdk_test.cpp
projects/abuild/test/toolchain_scanner_test.cpp
projects/abuild_old/project_scanner.cpp
projects/abuild_old/toolchain_scanner.cpp
projects/acore/acore.cpp
projects/acore/acore_common.cpp
projects/acore/process.cpp
projects/atest/atest.cpp

Abuild add sdk support #494

---

README.md
projects/command_line/documentation/high_level_design.md

[command_line] Add HLD #500

---

.github/pull_request_template.md

[devops] Add PR template #509

---

.gitignore

[devops] Update .gitignore #511

---

LICENSE

[devops] Update LICENSE #513

---

CODE_OF_CONDUCT.md

[devops] Add Code of Conduct #515

---

.github/ISSUE_TEMPLATE/bug.md
CONTRIBUTING.md

[devops] Add Contributing Guidelines #517

---

STYLE_GUIDE.md

[devops] Add style guide #519

---

.clang-format

[devops] Add .clang-format #525

---

style_guide.md

[devops] Add project & design sections to style guide #527

---

style_guide.md

[devops] Remove design section from the style_guide.md #529

---

adev.sh
sh/build.sh
sh/common.sh
sh/install.sh

[devops] Add adev.sh #531

---

projects/atest/atest.cpp
projects/atest/test/main.cpp

[atest] Add interface #533

---

sh/common_build.sh

[devops] Add MSVC support #535

---

sh/build_atest.sh
sh/common_build.sh

[atest] Add build script #537

---

adev.sh
sh/build.sh
sh/build_atest.sh
sh/common_build.sh

[devops] Add clang support #539

---

style_guide.md

[devops] Remove reference to ixx in style_guide.md #541

---

.gitignore

[devops] Add build/ to .gitignore #544

---

sh/build.sh
sh/build_atest.sh
sh/common_build.sh
sh/install.sh
sh/install_clang.sh

[devops] Add install clang package #547

---

sh/build_atest.sh
sh/common_build.sh
sh/install_clang.sh

[devops] Add suffix to clang on linux #549

---

.github/workflows/adev,yml
sh/common_build.sh

[devops] Add CI workflow #551

---

.github/workflows/adev,yml

[devops] Rename ADev workflow to adev #553

---

.github/workflows/adev.yml

[devops] Reinstate adev.yml workflow #558

---

readme.md

[devops] Add adev.yml workflow badge to readme #555

---

readme.md

[devops] Update main readme #561

---

sh/build_atest.sh

[atest] Fix main.obj being created in root #562

---

style_guide.md

[devops] Add requirement to fully qualify calls to free functions to style guide.md #570

---

style_guide.md

[devops] Swap mixedCase with snake_case for functions and variables in style guide.md #572

---

projects/astl/astl.hpp

[astl] Add astl.hpp #574

---

projects/astl/astl.cpp

[astl] Add astl.cpp #576

---

sh/build.sh
sh/build_atest.sh
sh/common_build.sh

[devops] Fix build command argument handling #579

---

projects/astl/astl.cpp
projects/atest/test/main.cpp

[astl] Add source_location #584

---

projects/astl/readme.md
readme.md

[astl] Add readme #586

---

projects/atest/atest.cpp
projects/atest/failed_assertion.cpp
readme.md
sh/build_atest.sh

[atest] Add failed assertion type #588

---

.github/workflows/adev.yml
readme.md

[devops] Disable GCC #593

---

projects/atest/atest.cpp
projects/atest/test.cpp
readme.md
sh/build_atest.sh

[atest] Add test type #592

---

projects/atest/atest.cpp
projects/atest/test_suite.cpp
sh/build_atest.sh

[atest] Add test suite type #596

---

projects/atest/atest.cpp
projects/atest/global_tests.cpp
sh/build_atest.sh

[atest] Add global tests type #598

---

projects/atest/atest.cpp
projects/atest/expect_base.cpp
sh/build_atest.sh

[atest] Add expect base class #600

---

projects/atest/atest.cpp
projects/atest/stringify.cpp
sh/build_atest.sh

[atest] Add stringify #602

---

projects/atest/atest.cpp
projects/atest/expect_to_match.cpp
sh/build_atest.sh

[atest] Add expect_to_match class #604

---

projects/astl/astl.cpp
projects/astl/convertible_to.hpp
projects/astl/invocable.hpp
projects/astl/source_location.hpp

[astl] Add clang missing concepts #607

---

projects/atest/atest.cpp
projects/atest/matcher_base.cpp
sh/build_atest.sh

[atest] Add matcher base class #610

---

projects/atest/atest.cpp
projects/atest/matcher.cpp
sh/build_atest.sh

[atest] Add matcher class #612

---

projects/atest/atest.cpp
projects/atest/report.cpp
sh/build_atest.sh

[atest] Add report type #615

---

projects/atest/atest.cpp
projects/atest/reporter.cpp
sh/build_atest.sh

[atest] Add reporter class #617

---

projects/atest/atest.cpp
projects/atest/test_runner.cpp
sh/build_atest.sh

[atest] Add test runner #569

---

projects/atest/atest.cpp
projects/atest/expect.cpp
sh/build_atest.sh

[atest] Add expect class #622

---

projects/atest/atest.cpp
projects/atest/expect.cpp

[atest] Add main API #621

---

projects/atest/atest.cpp
projects/atest/expect.cpp
projects/atest/expect_to_match.cpp
projects/atest/expect_to_throw.cpp
projects/atest/matcher_base.cpp
projects/atest/stringify.cpp
projects/atest/test/assert_test.cpp
projects/atest/test/bad_test_suite.cpp
projects/atest/test/expect_to_be_test.cpp
projects/atest/test/expect_to_match_test.cpp
projects/atest/test/expect_to_throw_test.cpp
projects/atest/test/main.cpp
projects/atest/test/printer_test.cpp
sh/build_atest.sh

[atest] Add tests #625

---

projects/atest/test/assert_test.cpp
projects/atest/test/expect_to_match_test.cpp

[atest] Remove template keyword from tests #627

---

sh/build_astl.sh
sh/build_atest.sh
sh/common_build.sh

[devops] Remove modules specific build dirs #629

---

sh/build.sh
sh/common_build.sh

[devops] Skip done projects on build #633

---

projects/astl/readme.md
projects/atest/readme.md

[atest] Add readme #635

---

style_guide.md

[devops] Update project name style #638

---

projects/acommandline/acommandline.cpp
projects/acommandline/option_data.cpp
sh/build_acommandline.sh

[acommandline] Add option data type #642

---

projects/acommandline/acommandline.cpp
projects/acommandline/option_builder_base.cpp
sh/build_acommandline.sh

[acommandline] Add option builder base class #644

---

projects/acommandline/acommandline.cpp
projects/acommandline/option_builder.cpp
projects/acommandline/option_builder_defined.cpp
projects/acommandline/option_builder_described.cpp
projects/acommandline/option_builder_named.cpp
projects/acommandline/option_builder_value.cpp
sh/build_acommandline.sh

[acommandline] Add option builder #646

---

projects/acommandline/option_matcher.cpp
sh/build_acommandline.sh

[acommandline] Add option matcher #649

---

projects/acommandline/acommandline.cpp
projects/acommandline/option_setter.cpp
sh/build_acommandline.sh

[acommandline] Add option setter #651

---

projects/acommandline/acommandline.cpp
projects/acommandline/command_line.cpp
projects/acommandline/option_data.cpp
projects/acommandline/option_setter.cpp
sh/build_acommandline.sh

[acommandline] Add command line parsing #648

---

projects/acommandline/acommandline.cpp
projects/acommandline/command_line.cpp
projects/acommandline/option_help_line.cpp
projects/acommandline/printer.cpp
sh/build_acommandline.sh

[acommandline] Add help #641

---

.gitignore

[devops] Ignore .vscode/ #656

---

projects/atest/atest.cpp
projects/atest/expect.cpp
projects/atest/expect_base.cpp
projects/atest/expect_to_match.cpp
projects/atest/expect_to_throw.cpp
projects/atest/failed_assertion.cpp
projects/atest/failure.cpp
projects/atest/global_tests.cpp
projects/atest/matcher.cpp
projects/atest/matcher_base.cpp
projects/atest/printer.cpp
projects/atest/report.cpp
projects/atest/reporter.cpp
projects/atest/stringify.cpp
projects/atest/test.cpp
projects/atest/test_runner.cpp
projects/atest/test_suite.cpp

[atest] Update documentation #664

---

projects/acommandline/command_line.cpp
projects/acommandline/option.cpp
projects/acommandline/option_builder.cpp
projects/acommandline/option_builder_base.cpp
projects/acommandline/option_builder_defined.cpp
projects/acommandline/option_builder_described.cpp
projects/acommandline/option_builder_named.cpp
projects/acommandline/option_builder_value.cpp
projects/acommandline/option_help_line.cpp
projects/acommandline/option_matcher.cpp
projects/acommandline/option_setter.cpp
projects/acommandline/printer.cpp

[acommandline] Add documentation #660

---

projects/atest/expect_to_throw.cpp
projects/atest/stringify.cpp

[atest] Fix missing docs #671

---

.github/workflows/adev.yml
sh/build.sh

[devops] Add documentation to build #665

---

adev.sh
sh/clang_tidy.sh

[devops] Add per project analysis #678

---

projects/atest/atest.cpp
projects/atest/expect_base.cpp
projects/atest/matcher_base.cpp
projects/atest/printer.cpp
projects/atest/reporter.cpp
projects/atest/stringify.cpp
projects/atest/test/assert_test.cpp
projects/atest/test/bad_test_suite.cpp
projects/atest/test/expect_to_be_test.cpp
projects/atest/test/expect_to_match_test.cpp
projects/atest/test/expect_to_throw_test.cpp
projects/atest/test/main.cpp
projects/atest/test/printer_test.cpp
projects/atest/test_runner.cpp

[atest] Fix clang-tidy warnings #681

---

projects/acommandline/acommandline.cpp
projects/acommandline/option.cpp
projects/acommandline/option_builder_described.cpp
projects/acommandline/option_help_line.cpp
projects/acommandline/option_matcher.cpp
projects/acommandline/option_setter.cpp
projects/acommandline/printer.cpp

[acommandline] Fix clang-tidy warnings #683

---

sh/common.sh

[devops] Add test sources to formatting #686

---

.github/workflows/pr.yml
sh/help.sh

[devops] Fix change to build files do not pass diff check #691

---

projects/acommandline/command_line.cpp
projects/acommandline/option_builder.cpp
projects/acommandline/test/command_line_test.cpp
projects/acommandline/test/examples.cpp
sh/build/acommandline_test.sh

[acommandline] Add examples to documentation #662

---

projects/acommandline/readme.md
projects/atest/readme.md
readme.md

[acommandline] Add readme #663

---

adev.sh
sh/build.sh
sh/build_common.sh
sh/coverage.sh
sh/help.sh

[devops] Add code coverage #696

---

readme.md
sh/build_common.sh
sh/coverage.sh

[atest] Fix code coverage #698

---

sh/analyse.sh

[devops] Fix modules diff not being analysed #701

---

projects/acommandline/command_line.cpp
projects/acommandline/option.cpp
projects/acommandline/option_builder_described.cpp
projects/acommandline/option_builder_value.cpp
projects/acommandline/option_help_line.cpp
projects/acommandline/option_setter.cpp
projects/acommandline/test/default_value_test.cpp
projects/acommandline/test/help_test.cpp
projects/acommandline/test/long_name_test.cpp
projects/acommandline/test/repeated_test.cpp
sh/coverage.sh

[acommandline] Fix code coverage #700

---

.github/workflows/adev.yml
.github/workflows/pr.yml

[devops] Add coverage to build #704

---

.github/workflows/adev.yml

[devops] Fix main workflow job name #706

---

.github/workflows/adev.yml
.github/workflows/pr.yml
sh/coverage.sh

[devops] Add build artifacts #709

---

sh/coverage.sh

[devops] Enable coverage option -show-line-counts-or-regions #716

---

readme.md

[devops] Update readme with docker info #718

---

.github/workflows/adev.yml
.github/workflows/pr.yml
sh/build.sh
sh/build_common.sh
sh/help.sh

[devops] Add address sanitizer #720

---

.github/workflows/adev.yml
.github/workflows/pr.yml
sh/build.sh
sh/build_common.sh
sh/help.sh

[devops] Add undefined behavior sanitizer #722

---

.github/workflows/adev.yml
.github/workflows/pr.yml
sh/build.sh
sh/build_common.sh
sh/help.sh

[devops] Add thread sanitizer #724

---

.github/workflows/adev.yml
.github/workflows/pr.yml
dockerfile
sh/build.sh
sh/build_common.sh
sh/build_libc++.sh
sh/common.sh
sh/docker.sh
sh/help.sh
sh/install/cmake.sh
sh/install/ninja.sh

[devops] Add memory sanitizer #726

---

projects/acommandline/command_line.cpp
projects/acommandline/option.cpp
projects/acommandline/option_setter.cpp
projects/acommandline/readme.md
projects/acommandline/test/application_name_test.cpp
projects/acommandline/test/command_line_test.cpp
projects/acommandline/test/command_test.cpp
projects/acommandline/test/default_value_test.cpp
projects/acommandline/test/examples.cpp
projects/acommandline/test/help_test.cpp
projects/acommandline/test/long_name_test.cpp
projects/acommandline/test/parse_test.cpp
projects/acommandline/test/positional_test.cpp
projects/acommandline/test/repeated_test.cpp
projects/acommandline/test/required_test.cpp
projects/acommandline/test/short_name_test.cpp
sh/coverage.sh

[acommandline] Add help displayed indicator #731

---

projects/atest/printer.cpp
projects/atest/readme.md
projects/atest/test/test_runner_test.cpp
projects/atest/test_runner.cpp

[atest] Add test listing #736

---

projects/astl/readme.md

[astl] Update readme regarding concepts in libc++ #747

---

projects/acommandline/readme.md
projects/atest/readme.md
projects/awinapi/readme.md

[devops] Fix internal readme links #750

---

projects/awinapi/awinapi.cpp

[awinapi] Add last error message() #745

---

projects/atest/test/main.cpp

[atest] Remove obsolete code from test main.cpp #755

---

.github/workflows/adev.yml
.github/workflows/pr.yml
compile_flags.txt
projects/acommandline/option_builder.cpp
projects/aprocess/test/main.cpp
projects/astl/astl.cpp
projects/astl/astl.hpp
projects/astl/test/source_location_test.cpp
projects/atest/test.cpp
projects/atest/test/main.cpp
projects/atest/test/throwing_suites_test.cpp
projects/atest/test_context.cpp
projects/atest/test_suite.cpp
projects/awinapi/buffer.cpp
projects/awinapi/last_error_message.cpp
projects/awinapi/test/buffer_test.cpp
projects/awinapi/test/handle_test.cpp
projects/awinapi/test/last_error_message_test.cpp
readme.md
sh/analyse.sh
sh/build/acommandline_test.sh
sh/build/aprocess_test.sh
sh/build/astl_test.sh
sh/build/atest_test.sh
sh/build/awinapi_test.sh
sh/build_common.sh
sh/coverage.sh

[devops] Enable windows clang build #761

---

.github/workflows/pr.yml
sh/analyse.sh

[devops] Fix out of memory in windows analysis #763

---

projects/aprocess/test/aprocesstestapp/main.cpp

[aprocess] Write test sometimes fail #770

---

projects/aprocess/test/read_test.cpp
projects/aprocess/test/write_test.cpp
projects/atest/expect_base.cpp
projects/atest/expect_to_match.cpp
projects/atest/expect_to_throw.cpp
projects/atest/failure.cpp
projects/atest/matcher.cpp
projects/atest/matcher_base.cpp
projects/atest/matcher_contains.cpp
projects/atest/printer.cpp
projects/atest/readme.md
projects/atest/test/expect_to_be_string_test.cpp
projects/atest/test/expect_to_match_test.cpp
projects/atest/test_runner.cpp
readme.md
sh/build/atest_test.sh
sh/coverage.sh

[atest] Improve string comparison reporting #769

---

.github/workflows/adev.yml
.github/workflows/pr.yml
readme.md
sh/build_common.sh

[devops] Use visual studio 2022 #777

---

projects/abuild/cpptokenizer/test/define_test.cpp
projects/abuild/cpptokenizer/tokenizer.cpp

[abuild] Fix defines in strings #781

---

readme.md
sh/coverage.sh

[devops] Fix aprocess_test coverage sometimes fail #772

---

projects/abuild/cpptokenizer/test/define_test.cpp
projects/abuild/cpptokenizer/test/tokenizer_test.cpp
projects/abuild/cpptokenizer/tokenizer.cpp

[abuild] Fix defines in raw string literals #784

---

projects/abuild/cpptokenizer/test/define_test.cpp
projects/abuild/cpptokenizer/test/undef_test.cpp
projects/abuild/cpptokenizer/token.cpp
projects/abuild/cpptokenizer/tokenizer.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add undef to tokenizer #786

---

projects/abuild/cpptokenizer/cpptokenizer.cpp
projects/abuild/cpptokenizer/if_token.cpp
projects/abuild/cpptokenizer/test/ifdef_test.cpp
projects/abuild/cpptokenizer/token.cpp
projects/abuild/cpptokenizer/tokenizer.cpp
sh/build/abuild.cpptokenizer.sh
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add ifdef to tokenizer #788

---

projects/abuild/cpptokenizer/if_token.cpp
projects/abuild/cpptokenizer/test/if_defined_test.cpp
projects/abuild/cpptokenizer/test/ifdef_test.cpp
projects/abuild/cpptokenizer/test/tokenizer_test.cpp
projects/abuild/cpptokenizer/tokenizer.cpp
sh/build/abuild.cpptokenizer_test.sh
sh/build_common.sh

[abuild] Add if defined to tokenizer #790

---

projects/abuild/cpptokenizer/if_token.cpp
projects/abuild/cpptokenizer/preprocessor_if_tokenizer.cpp
projects/abuild/cpptokenizer/preprocessor_tokenizer_common.cpp
projects/abuild/cpptokenizer/test/if_defined_test.cpp
projects/abuild/cpptokenizer/test/if_has_include_test.cpp
projects/abuild/cpptokenizer/token.cpp
projects/abuild/cpptokenizer/tokenizer_common.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add if __has_include to tokenizer #794

---

projects/aprocess/test/aprocesstestapp/main.cpp

[aprocess] Fix input test sometimes fail #797

---

projects/acommandline/option_builder_defined.cpp
projects/acommandline/option_builder_value.cpp
projects/aprocess/environment_variable.cpp
projects/atest/test_suite.cpp
sh/analyse.sh
sh/common.sh

[devops] Fix failed analysis does not fail build #799

---

projects/abuild/cpptokenizer/cpptokenizer.cpp
projects/abuild/cpptokenizer/preprocessor_tokenizer.cpp
projects/abuild/cpptokenizer/test/if_else_test.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add else to tokenizer #796

---

projects/abuild/cpptokenizer/preprocessor_if_tokenizer.cpp
projects/abuild/cpptokenizer/preprocessor_tokenizer.cpp
projects/abuild/cpptokenizer/preprocessor_tokenizer_common.cpp
projects/abuild/cpptokenizer/test/if_has_include_test.cpp
projects/abuild/cpptokenizer/test/include_external_test.cpp
projects/abuild/cpptokenizer/test/include_local_test.cpp
projects/abuild/cpptokenizer/tokenizer_common.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add include to tokenizer #802

---

projects/abuild/cpptokenizer/test/if_bracket_test.cpp
projects/abuild/cpptokenizer/test/if_defined_test.cpp
projects/abuild/cpptokenizer/test/if_else_test.cpp
projects/abuild/cpptokenizer/test/if_has_include_test.cpp
projects/abuild/cpptokenizer/test/if_test.cpp
projects/abuild/cpptokenizer/test/module_test.cpp
projects/abuild/cpptokenizer/test/tokenizer_test.cpp
projects/abuild/cpptokenizer/tokenizer.cpp
projects/abuild/cpptokenizer/tokenizer_common.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add module to tokenizer #804

---

projects/abuild/cpptokenizer/test/module_partition_test.cpp
projects/abuild/cpptokenizer/test/module_test.cpp
projects/abuild/cpptokenizer/tokenizer.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add module partition to tokenizer #806

---

projects/abuild/cpptokenizer/preprocessor_tokenizer_common.cpp
projects/abuild/cpptokenizer/test/import_include_external_test.cpp
projects/abuild/cpptokenizer/test/import_include_local_test.cpp
projects/abuild/cpptokenizer/test/include_local_test.cpp
projects/abuild/cpptokenizer/tokenizer.cpp
projects/abuild/cpptokenizer/tokenizer_common.cpp
sh/build/abuild.cpptokenizer_test.sh
sh/build_common.sh

[abuild] Add import header unit to tokenizer #808

---

projects/abuild/cpptokenizer/test/import_module_test.cpp
projects/abuild/cpptokenizer/test/module_partition_test.cpp
projects/abuild/cpptokenizer/test/module_test.cpp
projects/abuild/cpptokenizer/tokenizer.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add import module to tokenizer #810

---

projects/abuild/cpptokenizer/test/import_module_partition_test.cpp
projects/abuild/cpptokenizer/test/import_module_test.cpp
projects/abuild/cpptokenizer/tokenizer.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Add import module partition to tokenizer #812

---

projects/abuild/cpptokenizer/test/define_test.cpp
projects/abuild/cpptokenizer/test/import_module_partition_test.cpp
projects/abuild/cpptokenizer/test/import_module_test.cpp
projects/abuild/cpptokenizer/test/main.cpp
projects/abuild/cpptokenizer/test/module_partition_test.cpp
projects/abuild/cpptokenizer/test/module_test.cpp
projects/abuild/cpptokenizer/tokenizer_common.cpp
sh/build/abuild.cpptokenizer_test.sh

[abuild] Fix module tokens with dot in tokenizer #814

---

projects/aprocess/test/aprocesstestapp/main.cpp

[aprocess] Fix input example sometimes fail #816

---

projects/abuild/cache/cache.cpp
projects/abuild/cache/header_file.cpp
projects/abuild/cache/source_file.cpp
projects/abuild/cache/source_file_base.cpp
projects/abuild/cache/test/header_file_test.cpp
projects/abuild/cache/test/source_file_test.cpp
sh/build/abuild.cache.sh
sh/build/abuild.cache_test.sh

[abuild] Add SourceFile and HeaderFile #824

---

projects/abuild/cache/cache.cpp
projects/abuild/cache/project.cpp
projects/abuild/cache/test/project_test.cpp
sh/build/abuild.cache.sh
sh/build/abuild.cache_test.sh

[abuild] Add Project #825

---

projects/aprocess/test/examples.cpp

[aprocess] Fix examples failing #836

---

projects/abuild/cache/cache.cpp
projects/abuild/cache/cache_data.cpp
projects/abuild/cache/cache_impl.cpp
projects/abuild/cache/settings.cpp
projects/abuild/cache/test/settings_test.cpp
readme.md
sh/build/abuild.cache.sh
sh/build/abuild.cache_test.sh

[abuild] Add settings #838

---

projects/abuild/cache/test/file_lookup_test.cpp
projects/abuild/cache/test/tokens_test.cpp
projects/atest/atest.cpp
projects/atest/expect.cpp
projects/atest/readme.md
projects/atest/test/assert_test.cpp
projects/atest/test/expect_to_be_test.cpp
projects/atest/test/expect_to_contain_test.cpp
projects/atest/test/expect_to_match_test.cpp
projects/atest/test/expect_to_throw_test.cpp
projects/atest/test/test_filter_filter_suite_test.cpp
projects/atest/test/test_filter_filter_test_test.cpp
projects/atest/test/test_filter_suite_test.cpp
projects/atest/test/test_filter_test_test.cpp
projects/atest/test/test_runner_test.cpp
projects/awinapi/test/buffer_test.cpp
projects/awinapi/test/pipe_test.cpp

[atest] Add not_to_match() #841

---

projects/abuild/scanners/project_scanner.cpp
projects/abuild/scanners/scanners.cpp
projects/aprocess/unix_process.cpp
projects/athreadpool/queue.cpp
readme.md
sh/build/abuild.scanners.sh
sh/build/abuild.scanners_test.sh

[abuild] Use threadpool in scanners #846

---

readme.md
style_guide.md

[devops] Update style guide #851

---

.clang-tidy
containerfile
projects/aprocess/test/examples.cpp
projects/athreadpool/test/threadpool_test.cpp
sh/analyse.sh
sh/common.sh

[devops] Update llvm to 14.0.0 #853
